export const SUCCESS_REGISTER = "SUCCESS_REGISTER";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAIL_REGISTER = "FAIL_REGISTER";
export const FAIL_LOGIN = "FAIL_LOGIN";
export const USER_LOGOUT ="USER_LOGOUT";

export const LOAD_USER_SUCCESS ="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const RETURN_SECCESS = "RETURN_SECCESS"
  
export const LIST_USERS_SUCCESS ="LIST_USERS_SUCCESS";
export const LIST_USERS_FAIL = "LIST_USERS_FAIL";

export const JOB_LIST_SUCCESS = "JOB_LIST_SUCCESS";
export const JOB_LIST_FAIL = "JOB_LIST_FAIL";




